import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* ── SYNQ brand tokens ── */
        synq: {
          midnight:  '#0B1020',
          violet:    '#6D5EF9',
          'violet-dark': '#5B4FE8',
          cyan:      '#18D8FF',
          green:     '#21F2A6',
          amber:     '#FFB547',
          coral:     '#FF5C74',
          slate:     '#8A94A6',
          card:      '#111827',
          surface:   '#0F1525',
        },
        /* ── Legacy brand tokens (admin workspace depends on these) ── */
        brand: {
          dark:      '#0B1020',
          darker:    '#0B1020',
          navy:      '#111827',
          slate:     '#1E2A45',
          accent:    '#6D5EF9',
          'accent-dim': '#5B4FE8',
          cyan:      '#18D8FF',
          'cyan-dim':'#10B8D8',
          blue:      '#6D5EF9',
          warning:   '#FFB547',
          danger:    '#FF5C74',
          muted:     '#8A94A6',
          light:     '#E8E6FF',
        },
        /* ── SYNQ/SYNQ marketing design tokens ── */
        pg: {
          navy:       '#0B1020',
          blue:       '#6D5EF9',
          'blue-dark':'#5B4FE8',
          cyan:       '#18D8FF',
          success:    '#21F2A6',
          'gray-50':  '#F8FAFC',
          'gray-100': '#F1F5F9',
          'gray-200': '#E2E8F0',
          'gray-300': '#CBD5E1',
          'gray-400': '#94A3B8',
          'gray-500': '#64748B',
          'gray-700': '#334155',
          'gray-900': '#0F172A',
        },
        /* ── SYNQ "Stitch" design-system tokens (marketing site) ── */
        'midnight':                 '#0B1020',
        'deep-obsidian':            '#080D1A',
        'background':               '#13121b',
        'surface':                  '#13121b',
        'surface-dim':              '#13121b',
        'surface-bright':           '#393842',
        'surface-variant':          '#35343d',
        'surface-container-lowest': '#0e0d16',
        'surface-container-low':    '#1b1b24',
        'surface-container':        '#201f28',
        'surface-container-high':   '#2a2932',
        'surface-container-highest':'#35343d',
        'on-surface':               '#e5e0ee',
        'on-surface-variant':       '#c8c4d8',
        'on-background':            '#e5e0ee',
        'outline':                  '#928ea1',
        'outline-variant':          '#474555',
        'primary':                  '#c5c0ff',
        'primary-container':        '#6d5ef9',
        'on-primary':               '#2500a1',
        'on-primary-container':     '#ffffff',
        'secondary':                '#93e6ff',
        'secondary-container':      '#00d0f6',
        'secondary-fixed-dim':      '#1fd8ff',
        'on-secondary-container':   '#005566',
        'tertiary':                 '#00e299',
        'tertiary-container':       '#00875a',
        'on-tertiary':              '#003823',
        'on-tertiary-container':    '#ffffff',
        'glass-stroke':             'rgba(255, 255, 255, 0.08)',
        'glass-fill':               'rgba(8, 13, 26, 0.6)',
        'error':                    '#ffb4ab',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        /* ── Stitch typographic families ── */
        'display-xl':        ['var(--font-sora)', 'Sora', 'sans-serif'],
        'display-lg':        ['var(--font-sora)', 'Sora', 'sans-serif'],
        'display-lg-mobile': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'headline-md':       ['var(--font-sora)', 'Sora', 'sans-serif'],
        'body-md':           ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-lg':           ['var(--font-inter)', 'Inter', 'sans-serif'],
        'mono-label':        ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        'mono-data':         ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        /* ── Stitch type scale (name → [size, {lineHeight, weight, tracking}]) ── */
        'display-xl':        ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg':        ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md':       ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'mono-data':         ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'mono-label':        ['12px', { lineHeight: '1.3', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'unit':           '4px',
        'stack-xs':       '8px',
        'stack-md':       '24px',
        'stack-lg':       '48px',
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      boxShadow: {
        'pg-card': '0 4px 20px rgba(15,23,42,0.08)',
        'pg-card-hover': '0 20px 60px rgba(15,23,42,0.12)',
        'pg-cta': '0 20px 60px rgba(37,99,235,0.28)',
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'fade-in': 'fade-in 0.5s ease-out',
        'slide-up': 'slide-up 0.5s ease-out',
        'marquee': 'marquee 36s linear infinite',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0, 206, 200, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(0, 206, 200, 0.6)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'marquee': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
