/**
 * Comm Hub ("Pulse") backend — now on the SHARED Postgres so mentions,
 * conversations, connected channels and replies are consistent across
 * environments. `getDb()` returns the shared pool; all read/write helpers are
 * async.
 *
 * Mentions are REAL and PER-USER (ingested from external providers, scoped to
 * the authenticated user's company). All mention reads use one canonical window
 * (rolling MENTION_WINDOW_DAYS) so the list, KPI, badge and chart reconcile.
 */
import type { Pool } from 'pg';
import { randomBytes } from 'crypto';
import { appPool, ensureAppSchema } from '@/lib/app-pg';
import { migrateSqliteTable } from '@/lib/pg-migrate';

/** Canonical mention window shared by the list, count, badge and chart. */
export const MENTION_WINDOW_DAYS = 30;

let ready: Promise<void> | null = null;

/** Create the comms tables in Postgres and migrate any legacy comms.db rows. Cached. */
export function ensureCommsReady(): Promise<void> {
  if (ready) return ready;
  ready = (async () => {
    await ensureAppSchema();
    const p = appPool();
    await p.query(`CREATE TABLE IF NOT EXISTS conversations (
      id TEXT PRIMARY KEY, customer TEXT NOT NULL, initials TEXT NOT NULL, platform TEXT NOT NULL,
      sentiment TEXT NOT NULL, snippet TEXT NOT NULL, time_ago TEXT NOT NULL, unread INTEGER DEFAULT 1,
      location TEXT, language TEXT, intent TEXT, urgency INTEGER DEFAULT 5, first_contact TEXT,
      created_at BIGINT DEFAULT extract(epoch from now())::bigint)`);
    await p.query(`CREATE TABLE IF NOT EXISTS messages (
      id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, from_type TEXT NOT NULL, text TEXT NOT NULL,
      time TEXT NOT NULL, created_at BIGINT DEFAULT extract(epoch from now())::bigint)`);
    await p.query(`CREATE TABLE IF NOT EXISTS ai_replies (
      conversation_id TEXT PRIMARY KEY, text TEXT NOT NULL, updated_at BIGINT DEFAULT extract(epoch from now())::bigint)`);
    await p.query(`CREATE TABLE IF NOT EXISTS timeline_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id TEXT NOT NULL,
      date TEXT NOT NULL, channel TEXT NOT NULL, event TEXT NOT NULL)`);
    await p.query(`CREATE TABLE IF NOT EXISTS connected_channels (
      channel_id TEXT NOT NULL, handle TEXT NOT NULL, connected_at TEXT NOT NULL, user_id TEXT NOT NULL,
      PRIMARY KEY (user_id, channel_id))`);
    await p.query(`CREATE TABLE IF NOT EXISTS sent_replies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id TEXT NOT NULL, text TEXT NOT NULL,
      tone TEXT NOT NULL DEFAULT 'professional', kb_enabled INTEGER DEFAULT 1,
      sent_at BIGINT DEFAULT extract(epoch from now())::bigint)`);
    await p.query(`CREATE TABLE IF NOT EXISTS comms_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)`);
    await p.query(`CREATE TABLE IF NOT EXISTS mentions (
      id TEXT PRIMARY KEY, user_id TEXT, platform TEXT NOT NULL, author TEXT NOT NULL, handle TEXT NOT NULL,
      initials TEXT NOT NULL, text TEXT NOT NULL, url TEXT, time TEXT, sentiment TEXT NOT NULL DEFAULT 'neutral',
      context TEXT, provider TEXT, content_hash TEXT, detected_at BIGINT NOT NULL DEFAULT extract(epoch from now())::bigint,
      seen INTEGER NOT NULL DEFAULT 0, replied INTEGER NOT NULL DEFAULT 0,
      created_at BIGINT DEFAULT extract(epoch from now())::bigint)`);
    await p.query(`CREATE UNIQUE INDEX IF NOT EXISTS idx_mentions_user_hash ON mentions(user_id, content_hash)`);
    await p.query(`CREATE INDEX IF NOT EXISTS idx_mentions_user_detected ON mentions(user_id, detected_at DESC)`);

    // One-time migration of legacy comms.db rows (skips id on identity tables).
    await migrateSqliteTable({ file: 'comms.db', table: 'conversations', columns: ['id','customer','initials','platform','sentiment','snippet','time_ago','unread','location','language','intent','urgency','first_contact','created_at'], conflict: 'ON CONFLICT (id) DO NOTHING' });
    await migrateSqliteTable({ file: 'comms.db', table: 'messages', columns: ['id','conversation_id','from_type','text','time','created_at'], conflict: 'ON CONFLICT (id) DO NOTHING' });
    await migrateSqliteTable({ file: 'comms.db', table: 'ai_replies', columns: ['conversation_id','text','updated_at'], conflict: 'ON CONFLICT (conversation_id) DO NOTHING' });
    await migrateSqliteTable({ file: 'comms.db', table: 'connected_channels', columns: ['channel_id','handle','connected_at','user_id'], conflict: 'ON CONFLICT (user_id, channel_id) DO NOTHING' });
    await migrateSqliteTable({ file: 'comms.db', table: 'sent_replies', columns: ['conversation_id','text','tone','kb_enabled','sent_at'] });
    await migrateSqliteTable({ file: 'comms.db', table: 'timeline_events', columns: ['conversation_id','date','channel','event'] });
    await migrateSqliteTable({ file: 'comms.db', table: 'comms_meta', columns: ['key','value'], conflict: 'ON CONFLICT (key) DO NOTHING' });
    await migrateSqliteTable({ file: 'comms.db', table: 'mentions', columns: ['id','user_id','platform','author','handle','initials','text','url','time','sentiment','context','provider','content_hash','detected_at','seen','replied','created_at'], conflict: 'ON CONFLICT (id) DO NOTHING' });
  })().catch((err) => { ready = null; throw err; });
  return ready;
}

/** Returns the shared Postgres pool (kept for call-site parity). */
export function getDb(): Pool {
  return appPool();
}

async function db(): Promise<Pool> {
  await ensureCommsReady();
  return appPool();
}

/* ── comms_meta key/value (per-user watermarks etc.) ─────────────────────────── */

export async function getMeta(_db: Pool, key: string): Promise<string | null> {
  const p = await db();
  const r = await p.query('SELECT value FROM comms_meta WHERE key = $1', [key]);
  return (r.rows[0]?.value as string) ?? null;
}

export async function setMeta(_db: Pool, key: string, value: string): Promise<void> {
  const p = await db();
  await p.query('INSERT INTO comms_meta (key, value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value', [key, value]);
}

/* ── Mentions (real, per-user) ───────────────────────────────────────────────── */

function nowSec(): number { return Math.floor(Date.now() / 1000); }
function windowStart(days = MENTION_WINDOW_DAYS): number { return nowSec() - days * 86400; }

export type Sentiment = 'positive' | 'neutral' | 'negative';

export interface MentionRecord {
  id: string;
  user_id: string;
  platform: string;
  author: string;
  handle: string;
  initials: string;
  text: string;
  url: string;
  time: string;
  sentiment: string;
  context: string;
  provider: string | null;
  replied: number;
  seen: number;
  detected_at: number;
}

export interface MentionInsert {
  platform: string;
  author: string;
  handle: string;
  initials: string;
  text: string;
  url: string;
  sentiment: string;
  context: string;
  provider: string;
  content_hash: string;
  detected_at: number;
}

export interface MentionFilter {
  platform?: string;
  sentiment?: string;
  status?: 'all' | 'replied' | 'unreplied' | 'unseen';
  q?: string;
}

/** Build a parameterized WHERE clause starting placeholders at $1. */
function buildMentionWhere(userId: string, f: MentionFilter = {}): { sql: string; params: unknown[] } {
  const params: unknown[] = [];
  const clause = (frag: (i: number) => string, ...vals: unknown[]) => {
    const start = params.length + 1;
    params.push(...vals);
    return frag(start);
  };
  const clauses: string[] = [];
  clauses.push(clause((i) => `user_id = $${i}`, userId));
  clauses.push(clause((i) => `detected_at >= $${i}`, windowStart()));
  if (f.platform && f.platform !== 'all') clauses.push(clause((i) => `platform = $${i}`, f.platform));
  if (f.sentiment && f.sentiment !== 'all') clauses.push(clause((i) => `sentiment = $${i}`, f.sentiment));
  if (f.status === 'replied') clauses.push('replied = 1');
  else if (f.status === 'unreplied') clauses.push('replied = 0');
  else if (f.status === 'unseen') clauses.push('seen = 0');
  if (f.q && f.q.trim()) {
    const term = `%${f.q.trim()}%`;
    clauses.push(clause((i) => `(text ILIKE $${i} OR author ILIKE $${i + 1} OR handle ILIKE $${i + 2})`, term, term, term));
  }
  return { sql: `WHERE ${clauses.join(' AND ')}`, params };
}

/** A user's mentions within the canonical window, newest first. */
export async function listMentions(_db: Pool, userId: string, f: MentionFilter = {}, limit = 200): Promise<MentionRecord[]> {
  const p = await db();
  const { sql, params } = buildMentionWhere(userId, f);
  const rows = (await p.query(
    `SELECT id, user_id, platform, author, handle, initials, text, url, sentiment, context,
            provider, replied, seen, detected_at
     FROM mentions ${sql}
     ORDER BY detected_at DESC
     LIMIT $${params.length + 1}`,
    [...params, limit],
  )).rows as (Omit<MentionRecord, 'time' | 'detected_at'> & { detected_at: string | number })[];
  return rows.map((r) => ({ ...r, detected_at: Number(r.detected_at), time: relTime(Number(r.detected_at)) }));
}

export async function countMentions(_db: Pool, userId: string, f: MentionFilter = {}): Promise<number> {
  const p = await db();
  const { sql, params } = buildMentionWhere(userId, f);
  const r = await p.query(`SELECT COUNT(*)::int AS c FROM mentions ${sql}`, params);
  return (r.rows[0]?.c as number) ?? 0;
}

/** Mentions detected in the last 24h — used for the Basic-tier daily mentions cap. */
export async function countMentionsToday(_db: Pool, userId: string): Promise<number> {
  const p = await db();
  const r = await p.query('SELECT COUNT(*)::int AS c FROM mentions WHERE user_id = $1 AND detected_at >= $2', [userId, windowStart(1)]);
  return (r.rows[0]?.c as number) ?? 0;
}

/** Insert a freshly-ingested mention; ignores duplicates (user_id + content_hash). Returns true if inserted. */
export async function upsertMention(_db: Pool, userId: string, m: MentionInsert): Promise<boolean> {
  const p = await db();
  const r = await p.query(
    `INSERT INTO mentions (id, user_id, platform, author, handle, initials, text, url, time,
                           sentiment, context, provider, content_hash, detected_at, seen, replied)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'',$9,$10,$11,$12,$13,0,0)
     ON CONFLICT (user_id, content_hash) DO NOTHING`,
    [`mnt_${randomBytes(10).toString('hex')}`, userId, m.platform, m.author, m.handle, m.initials, m.text, m.url,
     m.sentiment, m.context, m.provider, m.content_hash, m.detected_at],
  );
  return (r.rowCount ?? 0) > 0;
}

/** Mark a user's mentions as seen (all in-window, or a specific id). */
export async function markMentionsSeen(_db: Pool, userId: string, id?: string): Promise<number> {
  const p = await db();
  const r = id
    ? await p.query('UPDATE mentions SET seen = 1 WHERE user_id = $1 AND id = $2', [userId, id])
    : await p.query('UPDATE mentions SET seen = 1 WHERE user_id = $1 AND seen = 0', [userId]);
  return r.rowCount ?? 0;
}

export async function markMentionReplied(_db: Pool, userId: string, id: string): Promise<boolean> {
  const p = await db();
  const r = await p.query('UPDATE mentions SET replied = 1, seen = 1 WHERE user_id = $1 AND id = $2', [userId, id]);
  return (r.rowCount ?? 0) > 0;
}

/* ── Recent activity feed + comms chart (derived from real events) ───────────── */

const PLATFORM_COLOR: Record<string, string> = {
  linkedin: '#0A66C2', x: '#e4e4e4', twitter: '#e4e4e4', whatsapp: '#25D366', email: '#6D5EF9',
  gmail: '#EA4335', instagram: '#E1306C', facebook: '#1877F2', tiktok: '#69C9D0',
  reddit: '#FF4500', youtube: '#FF0000', hackernews: '#FF6600', news: '#9CA3AF', web: '#9CA3AF',
};
export const platformColor = (p: string) => PLATFORM_COLOR[p] ?? '#6D5EF9';
export const platformLabel = (p: string) =>
  p === 'x' ? 'X' : p === 'hackernews' ? 'Hacker News' : p.charAt(0).toUpperCase() + p.slice(1);

function relTime(unixSec: number): string {
  const diff = nowSec() - unixSec;
  if (diff < 60) return 'just now';
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

/** Local Y-M-D key for a unix timestamp (matches the chart's local buckets). */
function localDayKey(unixSec: number): string {
  const d = new Date(unixSec * 1000);
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${d.getFullYear()}-${m}-${day}`;
}

export interface ActivityEvent { id: string; event: string; time: string; color: string; ts: number }

/**
 * Recent real events for a user: brand mentions detected + replies sent +
 * channels connected — within the window.
 */
export async function listRecentActivity(_db: Pool, userId: string, limit = 10): Promise<ActivityEvent[]> {
  const p = await db();
  const start = windowStart();
  const events: ActivityEvent[] = [];

  for (const m of await listMentions(_db, userId, {}, limit)) {
    events.push({
      id: `mention-${m.id}`,
      event: `New mention on ${platformLabel(m.platform)} · ${m.author}`,
      time: relTime(m.detected_at), color: platformColor(m.platform), ts: m.detected_at,
    });
  }

  const replies = (await p.query(
    `SELECT sr.id, sr.conversation_id, sr.sent_at, c.customer, c.platform
     FROM sent_replies sr
     LEFT JOIN conversations c ON c.id = sr.conversation_id
     WHERE sr.sent_at >= $1
     ORDER BY sr.sent_at DESC LIMIT $2`,
    [start, limit],
  )).rows as { id: number | string; conversation_id: string; sent_at: string | number; customer: string | null; platform: string | null }[];
  for (const r of replies) {
    const isMention = String(r.conversation_id).startsWith('mention:');
    const who = r.customer ?? (isMention ? 'a brand mention' : 'a contact');
    events.push({
      id: `reply-${r.id}`,
      event: `Reply sent to ${who}${r.platform ? ` on ${platformLabel(r.platform)}` : ''}`,
      time: relTime(Number(r.sent_at)), color: '#21F2A6', ts: Number(r.sent_at),
    });
  }

  const chans = (await p.query('SELECT channel_id, handle, connected_at FROM connected_channels WHERE user_id = $1', [userId]))
    .rows as { channel_id: string; handle: string; connected_at: string }[];
  for (const ch of chans) {
    const parsed = Math.floor(new Date(ch.connected_at).getTime() / 1000);
    const ts = Number.isFinite(parsed) && parsed > 0 ? parsed : nowSec();
    if (ts < start) continue;
    events.push({
      id: `chan-${ch.channel_id}`,
      event: `Channel connected · ${ch.handle}`,
      time: relTime(ts), color: platformColor(ch.channel_id), ts,
    });
  }

  return events.sort((a, b) => b.ts - a.ts).slice(0, limit);
}

export interface ActivityDay { day: string; received: number; sent: number; mentions: number }

/** Real messages-in / replies-out / mentions bucketed over the last 7 days (LOCAL day). */
export async function commsActivitySeries(_db: Pool, userId: string): Promise<ActivityDay[]> {
  const p = await db();
  const now = new Date();
  const buckets: (ActivityDay & { key: string })[] = [];
  for (let i = 6; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(now.getDate() - i);
    buckets.push({
      key: localDayKey(Math.floor(d.getTime() / 1000)),
      day: d.toLocaleDateString('en-US', { weekday: 'short' }),
      received: 0, sent: 0, mentions: 0,
    });
  }
  const byKey = Object.fromEntries(buckets.map((b) => [b.key, b]));
  const weekStart = Math.floor(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6).getTime() / 1000);

  ((await p.query('SELECT sent_at FROM sent_replies WHERE sent_at >= $1', [weekStart])).rows as { sent_at: string | number }[])
    .forEach((r) => { const b = byKey[localDayKey(Number(r.sent_at))]; if (b) b.sent++; });
  ((await p.query("SELECT created_at FROM messages WHERE from_type = 'customer' AND created_at >= $1", [weekStart])).rows as { created_at: string | number }[])
    .forEach((m) => { const b = byKey[localDayKey(Number(m.created_at))]; if (b) b.received++; });
  ((await p.query('SELECT detected_at FROM mentions WHERE user_id = $1 AND detected_at >= $2', [userId, weekStart])).rows as { detected_at: string | number }[])
    .forEach((m) => { const b = byKey[localDayKey(Number(m.detected_at))]; if (b) b.mentions++; });

  return buckets.map(({ day, received, sent, mentions }) => ({ day, received, sent, mentions }));
}
